import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';

await build({
  entryPoints: [fileURLToPath(new URL('./action.mjs', import.meta.url))],
  outfile: fileURLToPath(new URL('./action.bundle.mjs', import.meta.url)),
  bundle: true, platform: 'node', format: 'esm', target: 'node22',
  alias: { '@mikthatguy/momento-protocol': fileURLToPath(new URL('../packages/protocol/src/index.ts', import.meta.url)) },
  banner: { js: '// Generated by npm run build:action. Commit this file with Action changes.' }
});
